[build]
  command = "npm ci --force && npm run build"
  publish = "dist"

[build.environment]
  GO_VERSION = "none"
  PHP_VERSION = "none"
  RUBY_VERSION = "none"

[build.caching]
  directory = "node_modules"