[build]
  command = "npm install --force && npm run build"
  publish = "dist"  # Replace with your build output directory

[build.environment]
  NODE_VERSION = "18.20.6"  # Explicitly set Node.js version

[build.caching]
  directory = "node_modules"