[build]
  command = "npm install --force && npm run build"
  publish = "dist"  # Replace with your build output directory

[build.environment]
  NODE_VERSION = "18.20.6"  # Explicitly set Node.js version

[build.caching]
  directory = "node_modules"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/websockets",
    "@nestjs/microservices",
    "@fastify/static"
  ]
  included_files = [
    "src/mocks/game-data.json"
  ]

[[redirects]]
  from = "/get-all-games"
  to = "/.netlify/functions/getAllGames"
  status = 200

[[redirects]]
  from = "/search-games"
  to = "/.netlify/functions/searchGames"
  status = 200